// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssriinmsnbhafgijcxyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcmlpbm1zbmJoYWZnaWpjeHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyOTUwOTMsImV4cCI6MjA3Mzg3MTA5M30.eOG-dWNDk_7t7LAtac1x5UR_tzBnVYouErr-BXMKmW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});